---
service: yodle-hostname
plugins:
  - serverless-webpack
custom:
  webpack: ../../webpack.config.js
  webpackIncludeModules:
    packagePath: ../../package.json
provider:
  name: aws
  runtime: nodejs6.10
functions:
  gethostname:
    handler: handler.api
    memorysize: 128
    description: hostname query endpoint.
    events:
      - http:
          path: api/hostname
          method: any
